apiVersion: v1
kind: Service
metadata:
  name: internal-lb
  namespace: gohttpserver
  labels:
    run: gohttpserver
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: gohttpserver
