apiVersion: v1
kind: Service
metadata:
  name: public-lb
  namespace: gohttpserver
  labels:
    run: gohttpserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: gohttpserver
